// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

// import 'firebase_options.dart';

// await Firebase.initializeApp(
// options: DefaultFirebaseOptions.currentPlatform,
//  );
///
class DefaultFirebaseOptions {
  static const String messagingKey =
      'your_messaging_key_here'; //changes made here

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHXvmh6lxz2ulqnb9gJqgRhFraOInq9TA',
    appId: '1:278552563377:android:ad8965f5c80a38aecc9c90',
    messagingSenderId: '278552563377',
    projectId: 'chat-b3aa5',
    storageBucket: 'chat-b3aa5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBavw0mAE_7pmIzY0h6750S2XzHT-4KagE',
    appId: '1:278552563377:ios:b95c6646a4d733f8cc9c90',
    messagingSenderId: '278552563377',
    projectId: 'chat-b3aa5',
    storageBucket: 'chat-b3aa5.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2qwu_xk8n4zDCoU7-fqgDAptljvLsXM8',
    appId: '1:278552563377:web:a30607ee206a4910cc9c90',
    messagingSenderId: '278552563377',
    projectId: 'chat-b3aa5',
    authDomain: 'chat-b3aa5.firebaseapp.com',
    storageBucket: 'chat-b3aa5.appspot.com',
    measurementId: 'G-138H24Y6XY',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBavw0mAE_7pmIzY0h6750S2XzHT-4KagE',
    appId: '1:278552563377:ios:b95c6646a4d733f8cc9c90',
    messagingSenderId: '278552563377',
    projectId: 'chat-b3aa5',
    storageBucket: 'chat-b3aa5.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2qwu_xk8n4zDCoU7-fqgDAptljvLsXM8',
    appId: '1:278552563377:web:bb7ac77ad59b9673cc9c90',
    messagingSenderId: '278552563377',
    projectId: 'chat-b3aa5',
    authDomain: 'chat-b3aa5.firebaseapp.com',
    storageBucket: 'chat-b3aa5.appspot.com',
    measurementId: 'G-ZHG4ESN7DH',
  );
}
// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static const String messagingKey =
//       'your_messaging_key_here'; //changes made here

//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDngWgsN8n6EUCwrnk4bm9eab8kaEQuImE',
//     appId: '1:494357360726:android:8cd7413593b805f0f00bf7',
//     messagingSenderId: '494357360726',
//     projectId: 'chatapp-ba595',
//     storageBucket: 'chatapp-ba595.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDvVp33ZF--HHnrEb8TI_4WlMWrLg3pCig',
//     appId: '1:494357360726:ios:7c54efa39bb271aaf00bf7',
//     messagingSenderId: '494357360726',
//     projectId: 'chatapp-ba595',
//     storageBucket: 'chatapp-ba595.appspot.com',
//     iosBundleId: 'com.example.flutterApplication',
//   );

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDjqUN1ucG3_TASwS5DNjZW7xPfwK58Ooo',
//     appId: '1:494357360726:web:bf0e0c8010a88f6cf00bf7',
//     messagingSenderId: '494357360726',
//     projectId: 'chatapp-ba595',
//     authDomain: 'chatapp-ba595.firebaseapp.com',
//     storageBucket: 'chatapp-ba595.appspot.com',
//     measurementId: 'G-HZN61K95KF',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDvVp33ZF--HHnrEb8TI_4WlMWrLg3pCig',
//     appId: '1:494357360726:ios:7c54efa39bb271aaf00bf7',
//     messagingSenderId: '494357360726',
//     projectId: 'chatapp-ba595',
//     storageBucket: 'chatapp-ba595.appspot.com',
//     iosBundleId: 'com.example.flutterApplication',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDjqUN1ucG3_TASwS5DNjZW7xPfwK58Ooo',
//     appId: '1:494357360726:web:16d6aa1b2f3fc55ff00bf7',
//     messagingSenderId: '494357360726',
//     projectId: 'chatapp-ba595',
//     authDomain: 'chatapp-ba595.firebaseapp.com',
//     storageBucket: 'chatapp-ba595.appspot.com',
//     measurementId: 'G-B8YSKR1ERZ',
//   );

// }